// ============================================================================
// P7-MKT-POSTER-02 Product 模块定义（第六条 P01-P14）
// 每个Product含 approved/forbidden claims、卖点、免责声明、允许圈层渠道
// 价格不写死：priceKey 对应后台 Product Price SSOT
// ============================================================================

import type { Product, ProductId } from "./types";

export const PRODUCTS: Record<ProductId, Product> = {
  P01: {
    id: "P01",
    name: "国学综合",
    desc: "国学工具与经典学习综合",
    enabled: true,
    approvedClaims: ["常用国学工具集中使用", "经典知识与题库配套学习", "支持记录、练习与持续复习"],
    forbiddenClaims: ["全网最全", "全网第一", "吊打", "替代全部高价软件"],
    sellingPoints: ["常用国学工具集中使用", "经典知识与题库配套学习", "支持记录、练习与持续复习"],
    defaultDisclaimer: "general",
    allowedAudiences: ["A01", "A02", "A03", "A04", "A05", "A06", "A07", "A08"],
    allowedChannels: ["C01", "C02", "C03", "C04", "C05", "C06", "C07", "C08", "C09", "C10"],
  },
  P02: {
    id: "P02",
    name: "紫微排盘",
    desc: "紫微斗数排盘工具",
    enabled: true,
    approvedClaims: ["传统术数排盘工具", "随时查看排盘结果", "支持记录与研究"],
    forbiddenClaims: ["预测命运", "改命", "转运", "必中"],
    sellingPoints: ["传统术数排盘工具", "随时查看排盘结果", "支持记录与研究"],
    defaultDisclaimer: "yixue",
    allowedAudiences: ["A01", "A02", "A06", "A07"],
    allowedChannels: ["C01", "C02", "C03", "C04", "C05", "C07", "C08", "C10"],
  },
  P03: {
    id: "P03",
    name: "八字排盘",
    desc: "四柱八字排盘工具",
    enabled: true,
    approvedClaims: ["四柱排盘工具", "干支查询", "传统历法参考"],
    forbiddenClaims: ["预测未来", "改运", "消灾", "破解"],
    sellingPoints: ["四柱排盘工具", "干支查询", "传统历法参考"],
    defaultDisclaimer: "yixue",
    allowedAudiences: ["A02", "A03", "A04", "A06"],
    allowedChannels: ["C01", "C02", "C03", "C04", "C05", "C07", "C08", "C10"],
  },
  P04: {
    id: "P04",
    name: "奇门排盘",
    desc: "奇门遁甲排盘工具",
    enabled: true,
    approvedClaims: ["奇门排盘工具", "传统文化研习"],
    forbiddenClaims: ["预测吉凶", "破解", "改命"],
    sellingPoints: ["奇门排盘工具", "传统文化研习"],
    defaultDisclaimer: "yixue",
    allowedAudiences: ["A06", "A02"],
    allowedChannels: ["C01", "C02", "C03", "C07", "C08", "C10"],
  },
  P05: {
    id: "P05",
    name: "六爻排盘",
    desc: "六爻排盘工具",
    enabled: true,
    approvedClaims: ["六爻排盘工具", "装卦纳甲查询", "传统文化研习"],
    forbiddenClaims: ["占卜必中", "预测吉凶", "消灾"],
    sellingPoints: ["六爻排盘工具", "装卦纳甲查询", "传统文化研习"],
    defaultDisclaimer: "yixue",
    allowedAudiences: ["A06", "A02"],
    allowedChannels: ["C01", "C02", "C03", "C07", "C08", "C10"],
  },
  P06: {
    id: "P06",
    name: "塔罗",
    desc: "塔罗符号文化体验",
    enabled: true,
    approvedClaims: ["符号文化体验", "兴趣探索", "自我观察"],
    forbiddenClaims: ["预测未来", "治愈焦虑", "解决迷茫"],
    sellingPoints: ["符号文化体验", "兴趣探索", "自我观察"],
    defaultDisclaimer: "general",
    allowedAudiences: ["A01", "A07"],
    allowedChannels: ["C01", "C02", "C03", "C06", "C07", "C08", "C10"],
  },
  P07: {
    id: "P07",
    name: "星座",
    desc: "星象符号文化",
    enabled: true,
    approvedClaims: ["星象符号查询", "兴趣体验", "朋友互动"],
    forbiddenClaims: ["预测未来", "治愈", "星座改运"],
    sellingPoints: ["星象符号查询", "兴趣体验", "朋友互动"],
    defaultDisclaimer: "general",
    allowedAudiences: ["A01", "A07"],
    allowedChannels: ["C01", "C02", "C03", "C06", "C07", "C08", "C10"],
  },
  P08: {
    id: "P08",
    name: "数字文化",
    desc: "东方数理文化工具",
    enabled: true,
    approvedClaims: ["东方数理文化", "趣味查询", "文化研习"],
    forbiddenClaims: ["数字改运", "预测吉凶"],
    sellingPoints: ["东方数理文化", "趣味查询", "文化研习"],
    defaultDisclaimer: "yixue",
    allowedAudiences: ["A01", "A02", "A07"],
    allowedChannels: ["C01", "C02", "C03", "C07", "C08", "C10"],
  },
  P09: {
    id: "P09",
    name: "中医经典学习",
    desc: "中医典籍与知识学习",
    enabled: true,
    approvedClaims: ["中医经典结构化整理", "知识点配套练习", "错题持续复习", "学习路线"],
    forbiddenClaims: ["治疗", "疗效", "调理疾病", "颐养延年", "改善症状", "根治", "治愈"],
    sellingPoints: ["经典内容结构化整理", "知识点配套练习", "错题持续复习"],
    defaultDisclaimer: "zhongyi",
    allowedAudiences: ["A03", "A04", "A05", "A08"],
    allowedChannels: ["C01", "C02", "C03", "C04", "C05", "C06", "C07", "C08", "C09", "C10"],
  },
  P10: {
    id: "P10",
    name: "医考题库",
    desc: "医考学习题库",
    enabled: true,
    approvedClaims: ["题库练习", "模拟练习", "错题复习"],
    forbiddenClaims: ["包过", "必中", "保过", "百分百"],
    sellingPoints: ["题库练习", "模拟练习", "错题复习"],
    defaultDisclaimer: "zhongyi",
    allowedAudiences: ["A05", "A08"],
    allowedChannels: ["C01", "C02", "C03", "C04", "C05", "C07", "C08", "C10"],
    priceKey: "tcm_question_bank",
  },
  P11: {
    id: "P11",
    name: "AI资料变题库",
    desc: "上传资料 AI整理知识点生成练习题",
    enabled: true,
    approvedClaims: ["上传资料自动整理", "AI知识点提取", "自动生成练习题", "错题复习"],
    forbiddenClaims: ["百分百准确", "包过", "必中"],
    sellingPoints: ["资料整理", "知识提取", "练习题", "错题复习"],
    defaultDisclaimer: "ai_learning",
    allowedAudiences: ["A01", "A02", "A03", "A05", "A06", "A07", "A08"],
    allowedChannels: ["C01", "C02", "C03", "C04", "C05", "C06", "C07", "C08", "C09", "C10"],
  },
  P12: {
    id: "P12",
    name: "学习空间",
    desc: "团队学习空间",
    enabled: true,
    approvedClaims: ["资料库与题库共享", "学习任务与进度", "成员练习与排行"],
    forbiddenClaims: ["躺赚", "团队赚钱"],
    sellingPoints: ["资料库与题库共享", "学习任务与进度", "成员练习与排行"],
    defaultDisclaimer: "general",
    allowedAudiences: ["A05", "A08", "A02"],
    allowedChannels: ["C01", "C02", "C03", "C04", "C05", "C07", "C08", "C10"],
  },
  P13: {
    id: "P13",
    name: "综合学习",
    desc: "经典学习与练习综合",
    enabled: true,
    approvedClaims: ["经典阅读", "学习笔记", "练习巩固"],
    forbiddenClaims: ["治愈迷茫", "根治"],
    sellingPoints: ["经典阅读", "学习笔记", "练习巩固"],
    defaultDisclaimer: "general",
    allowedAudiences: ["A03", "A04", "A05", "A08"],
    allowedChannels: ["C01", "C02", "C03", "C04", "C05", "C06", "C07", "C08", "C09", "C10"],
  },
  P14: {
    id: "P14",
    name: "APP综合推广",
    desc: "言道国学APP整体推广",
    enabled: true,
    approvedClaims: ["国学与学习工具，一处集合", "常用功能集中使用，减少来回切换", "多一个观察自己与生活的角度"],
    forbiddenClaims: ["全网最全医易综合工具箱", "功能吊打市面高价软件", "告别高价付费"],
    sellingPoints: ["国学与学习工具，一处集合", "常用功能集中使用", "经典学习与AI题库"],
    defaultDisclaimer: "general",
    allowedAudiences: ["A01", "A02", "A03", "A04", "A05", "A06", "A07", "A08"],
    allowedChannels: ["C01", "C02", "C03", "C04", "C05", "C06", "C07", "C08", "C09", "C10"],
  },
};

export const PRODUCT_LIST = Object.values(PRODUCTS).filter((p) => p.enabled);

export function getProduct(id: ProductId): Product {
  return PRODUCTS[id] ?? PRODUCTS.P14;
}
