/**
 * 董氏奇穴数据
 * 原始来源：自研整理，MIT License
 * 基于董景昌《董氏针灸正经奇穴学》整理
 * 修改记录：2026-08-05 初始版本
 * 当前协议：MIT
 */

import type { TcmDongAcupoint } from "@/algorithm-core/types/tcm";

/** 董氏奇穴部位分类 */
export const DONG_ZONES: Record<string, string> = {
  "zone_1": "一一部位（手指）",
  "zone_2": "二二部位（手掌）",
  "zone_3": "三三部位（前臂）",
  "zone_4": "四四部位（上臂）",
  "zone_5": "五五部位（足趾）",
  "zone_6": "六六部位（足掌）",
  "zone_7": "七七部位（小腿）",
  "zone_8": "八八部位（大腿）",
  "zone_9": "九九部位（耳朵）",
  "zone_10": "十十部位（头面）",
  "zone_11": "背部部位",
  "zone_12": "前胸部位",
};

/** 董氏奇穴完整数据库 */
export const DONG_ACUPOINTS_DB: TcmDongAcupoint[] = [
  // ============ 一一部位（手指） ============
  {
    name: "木穴",
    pinyin: "Mù Xué",
    code: "DT.01",
    zone: "一一部位（手指）",
    location: "食指掌面第一节中央线（D线）",
    location_detail: "在食指掌面第一节中央线（D线），距第一节横纹三分处。共三穴，采用三分点法。",
    function: "清利头目，开窍通络。主治：目赤肿痛、迎风流泪、鼻塞流涕、头痛、三叉神经痛。",
    needling_method: "直刺1-2分，或点刺出血。",
    depth: "1-2分",
    duration: "15-20分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "心常穴",
    pinyin: "Xīn Cháng Xué",
    code: "DT.02",
    zone: "一一部位（手指）",
    location: "中指掌面第一节中央线（D线）",
    location_detail: "在中指掌面第一节中央线（D线），距第一节横纹三分处。共三穴。",
    function: "宁心安神，宽胸理气。主治：心悸、怔忡、胸闷、胸痛、心律不齐。",
    needling_method: "直刺1-2分。",
    depth: "1-2分",
    duration: "15-20分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "脾肿穴",
    pinyin: "Pí Zhǒng Xué",
    code: "DT.03",
    zone: "一一部位（手指）",
    location: "中指掌面第二节中央线（D线）",
    location_detail: "在中指掌面第二节中央线（D线），距第二节横纹三分处。共三穴。",
    function: "健脾消肿，利水渗湿。主治：脾肿大、消化不良、水肿、四肢沉重。",
    needling_method: "直刺1-2分。",
    depth: "1-2分",
    duration: "15-20分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "复原穴",
    pinyin: "Fù Yuán Xué",
    code: "DT.04",
    zone: "一一部位（手指）",
    location: "无名指掌面第一节中央线（D线）",
    location_detail: "在无名指掌面第一节中央线（D线），距第一节横纹三分处。共三穴。",
    function: "补益肝肾，强筋健骨。主治：腰膝酸软、骨刺、骨质疏松、骨折后恢复。",
    needling_method: "直刺1-2分。",
    depth: "1-2分",
    duration: "15-20分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "五虎穴",
    pinyin: "Wǔ Hǔ Xué",
    code: "DT.05",
    zone: "一一部位（手指）",
    location: "拇指掌面第一节外侧赤白肉际处",
    location_detail: "在拇指掌面第一节外侧赤白肉际处，距第一节横纹三分处。共五穴，按指节等分。",
    function: "通经活络，消肿止痛。主治：全身各处关节疼痛、扭伤、手指麻木、腱鞘炎。",
    needling_method: "直刺1-2分，或点刺出血。",
    depth: "1-2分",
    duration: "15-20分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },

  // ============ 二二部位（手掌） ============
  {
    name: "重子穴",
    pinyin: "Zhòng Zǐ Xué",
    code: "DT.11",
    zone: "二二部位（手掌）",
    location: "手掌面，食指与中指之间，距掌指横纹一寸处",
    location_detail: "在手掌面，食指与中指之间，距掌指横纹一寸处（即虎口上约一寸）。",
    function: "清肺止咳，利咽消肿。主治：咳嗽、气喘、咽喉肿痛、感冒发热。",
    needling_method: "直刺3-5分。",
    depth: "3-5分",
    duration: "20-30分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "重仙穴",
    pinyin: "Zhòng Xiān Xué",
    code: "DT.12",
    zone: "二二部位（手掌）",
    location: "手掌面，中指与无名指之间，距掌指横纹一寸处",
    location_detail: "在手掌面，中指与无名指之间，距掌指横纹一寸处。",
    function: "清热解毒，消肿散结。主治：乳腺炎、乳腺增生、胸胁痛、背痛。",
    needling_method: "直刺3-5分。",
    depth: "3-5分",
    duration: "20-30分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "灵骨穴",
    pinyin: "Líng Gǔ Xué",
    code: "DT.13",
    zone: "二二部位（手掌）",
    location: "手背，第一掌骨与第二掌骨之间，距骨叉一寸处",
    location_detail: "在手背，第一掌骨与第二掌骨之间，距两骨叉口约一寸处。与合谷穴相近，但在筋骨之间。",
    function: "补气温阳，通经活络。主治：气虚乏力、面色萎黄、半身不遂、坐骨神经痛、腰痛。",
    needling_method: "直刺1-1.5寸，针感可传至肘肩。",
    depth: "1-1.5寸",
    duration: "20-30分钟",
    contraindications: "孕妇禁针。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "大白穴",
    pinyin: "Dà Bái Xué",
    code: "DT.14",
    zone: "二二部位（手掌）",
    location: "手背，第二掌骨桡侧，掌指关节后方凹陷处",
    location_detail: "在手背，第二掌骨桡侧，掌指关节后方凹陷处（握拳时明显）。",
    function: "清热止痛，通经活络。主治：头痛、牙痛、面神经麻痹、小儿惊风。",
    needling_method: "直刺0.5-1寸。",
    depth: "0.5-1寸",
    duration: "15-20分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },

  // ============ 三三部位（前臂） ============
  {
    name: "其门穴",
    pinyin: "Qí Mén Xué",
    code: "DT.21",
    zone: "三三部位（前臂）",
    location: "前臂掌侧，腕横纹上二寸，桡侧腕屈肌腱桡侧",
    location_detail: "在前臂掌侧，腕横纹上二寸，桡侧腕屈肌腱桡侧。",
    function: "理气和胃，降逆止呕。主治：胃痛、呕吐、腹胀、消化不良。",
    needling_method: "直刺0.5-1寸。",
    depth: "0.5-1寸",
    duration: "20-30分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "其角穴",
    pinyin: "Qí Jiǎo Xué",
    code: "DT.22",
    zone: "三三部位（前臂）",
    location: "前臂掌侧，腕横纹上四寸，桡侧腕屈肌腱桡侧",
    location_detail: "在前臂掌侧，腕横纹上四寸，桡侧腕屈肌腱桡侧。",
    function: "疏肝理气，和胃止痛。主治：肝气郁结、胃脘痛、胁痛、月经不调。",
    needling_method: "直刺0.5-1寸。",
    depth: "0.5-1寸",
    duration: "20-30分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "其正穴",
    pinyin: "Qí Zhèng Xué",
    code: "DT.23",
    zone: "三三部位（前臂）",
    location: "前臂掌侧，腕横纹上六寸，桡侧腕屈肌腱桡侧",
    location_detail: "在前臂掌侧，腕横纹上六寸，桡侧腕屈肌腱桡侧。",
    function: "调和气血，理气止痛。主治：胃十二指肠溃疡、慢性胃炎、胃下垂。",
    needling_method: "直刺0.5-1寸。",
    depth: "0.5-1寸",
    duration: "20-30分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "火串穴",
    pinyin: "Huǒ Chuàn Xué",
    code: "DT.24",
    zone: "三三部位（前臂）",
    location: "前臂背侧，腕背横纹上二寸五分，尺桡骨之间",
    location_detail: "在前臂背侧，腕背横纹上二寸五分，尺骨与桡骨之间。与外关穴相近。",
    function: "清热泻火，通经活络。主治：热病、头痛、目赤、耳鸣、便秘。",
    needling_method: "直刺0.5-1寸。",
    depth: "0.5-1寸",
    duration: "15-20分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "火陵穴",
    pinyin: "Huǒ Líng Xué",
    code: "DT.25",
    zone: "三三部位（前臂）",
    location: "前臂背侧，腕背横纹上四寸，尺桡骨之间",
    location_detail: "在前臂背侧，腕背横纹上四寸，尺骨与桡骨之间。",
    function: "清泻三焦之火，通络止痛。主治：三焦火盛、胸胁胀痛、肩臂痛。",
    needling_method: "直刺0.5-1寸。",
    depth: "0.5-1寸",
    duration: "15-20分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },

  // ============ 四四部位（上臂） ============
  {
    name: "分金穴",
    pinyin: "Fēn Jīn Xué",
    code: "DT.31",
    zone: "四四部位（上臂）",
    location: "上臂后侧，肩髎穴下三寸，肱骨后缘",
    location_detail: "在上臂后侧，肩髎穴（肩峰后下方凹陷）下三寸，肱骨后缘。",
    function: "清热化痰，止咳平喘。主治：感冒、咳嗽、支气管炎、过敏性鼻炎。",
    needling_method: "直刺1-1.5寸。",
    depth: "1-1.5寸",
    duration: "20-30分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "内金穴",
    pinyin: "Nèi Jīn Xué",
    code: "DT.32",
    zone: "四四部位（上臂）",
    location: "上臂后侧，分金穴下三寸",
    location_detail: "在上臂后侧，分金穴下三寸，肱骨后缘。",
    function: "健脾消食，化积导滞。主治：消化不良、食积、腹胀、小儿疳积。",
    needling_method: "直刺1-1.5寸。",
    depth: "1-1.5寸",
    duration: "20-30分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },

  // ============ 五五部位（足趾） ============
  {
    name: "火包穴",
    pinyin: "Huǒ Bāo Xué",
    code: "DT.41",
    zone: "五五部位（足趾）",
    location: "足大趾掌面，趾甲角旁开一分",
    location_detail: "在足大趾掌面，趾甲角旁开一分（相当于隐白穴附近）。",
    function: "清心泻火，凉血止血。主治：心火亢盛、口舌生疮、心烦失眠、鼻衄。",
    needling_method: "直刺1分，或点刺出血。",
    depth: "1分",
    duration: "15-20分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "上瘤穴",
    pinyin: "Shàng Liú Xué",
    code: "DT.42",
    zone: "五五部位（足趾）",
    location: "足底，足跟正中央点",
    location_detail: "在足底，足跟正中央点（跟骨结节处）。",
    function: "化瘀散结，通络止痛。主治：脑瘤、脑积水、头痛、癫痫。",
    needling_method: "直刺3-5分。",
    depth: "3-5分",
    duration: "20-30分钟",
    contraindications: "孕妇禁针。",
    literature: "《董氏针灸正经奇穴学》",
  },

  // ============ 七七部位（小腿） ============
  {
    name: "正筋穴",
    pinyin: "Zhèng Jīn Xué",
    code: "DT.51",
    zone: "七七部位（小腿）",
    location: "小腿后侧，跟腱正中央",
    location_detail: "在小腿后侧，跟腱正中央，约当昆仑与太溪连线中点上方。",
    function: "舒筋活络，强腰健膝。主治：腰脊痛、颈椎病、落枕、足跟痛。",
    needling_method: "直刺0.5-1寸，针尖需达跟腱中央。",
    depth: "0.5-1寸",
    duration: "20-30分钟",
    contraindications: "不可深刺损伤跟腱。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "正宗穴",
    pinyin: "Zhèng Zōng Xué",
    code: "DT.52",
    zone: "七七部位（小腿）",
    location: "小腿后侧，正筋穴上二寸",
    location_detail: "在小腿后侧，正筋穴上二寸，跟腱上。",
    function: "补肾壮腰，强筋健骨。主治：腰椎间盘突出、坐骨神经痛、下肢痿痹。",
    needling_method: "直刺0.5-1寸。",
    depth: "0.5-1寸",
    duration: "20-30分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "正士穴",
    pinyin: "Zhèng Shì Xué",
    code: "DT.53",
    zone: "七七部位（小腿）",
    location: "小腿后侧，正宗穴上二寸",
    location_detail: "在小腿后侧，正宗穴上二寸，跟腱上。",
    function: "强腰补肾，通络止痛。主治：腰肌劳损、腰椎骨质增生、肾虚腰痛。",
    needling_method: "直刺0.5-1寸。",
    depth: "0.5-1寸",
    duration: "20-30分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "一重穴",
    pinyin: "Yī Chóng Xué",
    code: "DT.54",
    zone: "七七部位（小腿）",
    location: "小腿外侧，外踝尖上三寸，腓骨前缘",
    location_detail: "在小腿外侧，外踝尖直上三寸，腓骨前缘。与悬钟穴相近。",
    function: "活血化瘀，消肿散结。主治：甲状腺肿大、淋巴结结核、乳腺增生。",
    needling_method: "直刺1-1.5寸。",
    depth: "1-1.5寸",
    duration: "20-30分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "二重穴",
    pinyin: "Èr Chóng Xué",
    code: "DT.55",
    zone: "七七部位（小腿）",
    location: "小腿外侧，一重穴上二寸",
    location_detail: "在小腿外侧，一重穴上二寸，腓骨前缘。",
    function: "软坚散结，活血化瘀。主治：各种肿瘤、囊肿、瘰疬。",
    needling_method: "直刺1-1.5寸。",
    depth: "1-1.5寸",
    duration: "20-30分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "三重穴",
    pinyin: "Sān Chóng Xué",
    code: "DT.56",
    zone: "七七部位（小腿）",
    location: "小腿外侧，二重穴上二寸",
    location_detail: "在小腿外侧，二重穴上二寸，腓骨前缘。",
    function: "化瘀散结，消肿止痛。主治：各种顽固性肿瘤、癌症辅助治疗。",
    needling_method: "直刺1-1.5寸。",
    depth: "1-1.5寸",
    duration: "20-30分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },

  // ============ 八八部位（大腿） ============
  {
    name: "通关穴",
    pinyin: "Tōng Guān Xué",
    code: "DT.61",
    zone: "八八部位（大腿）",
    location: "大腿前面正中线，髌骨底上五寸",
    location_detail: "在大腿前面正中线上，髌骨底上五寸。",
    function: "清心泻火，镇惊安神。主治：心脏病、心悸、心绞痛、心肌炎。",
    needling_method: "直刺1-2寸。",
    depth: "1-2寸",
    duration: "20-30分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "通山穴",
    pinyin: "Tōng Shān Xué",
    code: "DT.62",
    zone: "八八部位（大腿）",
    location: "大腿前面正中线，通关穴上二寸",
    location_detail: "在大腿前面正中线上，通关穴直上二寸。",
    function: "活血化瘀，通络止痛。主治：心前区痛、胸闷、心绞痛。",
    needling_method: "直刺1-2寸。",
    depth: "1-2寸",
    duration: "20-30分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "通天穴",
    pinyin: "Tōng Tiān Xué",
    code: "DT.63",
    zone: "八八部位（大腿）",
    location: "大腿前面正中线，通山穴上二寸",
    location_detail: "在大腿前面正中线上，通山穴直上二寸。",
    function: "清心降火，宁心安神。主治：心律不齐、心动过速、高血压。",
    needling_method: "直刺1-2寸。",
    depth: "1-2寸",
    duration: "20-30分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "姐妹一穴",
    pinyin: "Jiě Mèi Yī Xué",
    code: "DT.64",
    zone: "八八部位（大腿）",
    location: "大腿内侧，通肾穴上一寸",
    location_detail: "在大腿内侧，通肾穴（髌底内侧端上七寸）直上一寸。",
    function: "调理冲任，活血化瘀。主治：月经不调、痛经、子宫肌瘤、带下病。",
    needling_method: "直刺1-1.5寸。",
    depth: "1-1.5寸",
    duration: "20-30分钟",
    contraindications: "孕妇禁针。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "姐妹二穴",
    pinyin: "Jiě Mèi Èr Xué",
    code: "DT.65",
    zone: "八八部位（大腿）",
    location: "大腿内侧，姐妹一穴上二寸",
    location_detail: "在大腿内侧，姐妹一穴直上二寸。",
    function: "调经止痛，活血化瘀。主治：闭经、月经后期、不孕症。",
    needling_method: "直刺1-1.5寸。",
    depth: "1-1.5寸",
    duration: "20-30分钟",
    contraindications: "孕妇禁针。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "姐妹三穴",
    pinyin: "Jiě Mèi Sān Xué",
    code: "DT.66",
    zone: "八八部位（大腿）",
    location: "大腿内侧，姐妹二穴上二寸",
    location_detail: "在大腿内侧，姐妹二穴直上二寸。",
    function: "调经养血，散结消肿。主治：卵巢囊肿、子宫内膜异位症、更年期综合征。",
    needling_method: "直刺1-1.5寸。",
    depth: "1-1.5寸",
    duration: "20-30分钟",
    contraindications: "孕妇禁针。",
    literature: "《董氏针灸正经奇穴学》",
  },

  // ============ 九九部位（耳朵） ============
  {
    name: "耳背穴",
    pinyin: "Ěr Bèi Xué",
    code: "DT.71",
    zone: "九九部位（耳朵）",
    location: "耳背，耳廓背面中央",
    location_detail: "在耳背，耳廓背面中央，寻找明显静脉怒张处。",
    function: "清热泻火，凉血降压。主治：高血压、头痛、目赤肿痛、急性结膜炎。",
    needling_method: "用三棱针点刺怒张静脉，放出少量血液。",
    depth: "点刺出血",
    duration: "点刺即出",
    contraindications: "出血性疾病患者禁刺。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "木耳穴",
    pinyin: "Mù Ěr Xué",
    code: "DT.72",
    zone: "九九部位（耳朵）",
    location: "耳廓正面，耳甲腔中央",
    location_detail: "在耳廓正面，耳甲腔中央凹陷处。",
    function: "疏肝利胆，清利湿热。主治：肝炎、胆囊炎、胆结石、黄疸。",
    needling_method: "直刺1-2分。",
    depth: "1-2分",
    duration: "15-20分钟",
    contraindications: "注意消毒，防止感染。",
    literature: "《董氏针灸正经奇穴学》",
  },

  // ============ 十十部位（头面） ============
  {
    name: "正会穴",
    pinyin: "Zhèng Huì Xué",
    code: "DT.81",
    zone: "十十部位（头面）",
    location: "头顶正中，两耳尖连线中点",
    location_detail: "在头顶正中线上，两耳尖连线与正中线交点处（与百会穴相近）。",
    function: "升阳举陷，醒脑开窍。主治：头晕、目眩、脱肛、子宫脱垂、低血压。",
    needling_method: "平刺0.5-1寸。可灸。",
    depth: "0.5-1寸",
    duration: "20-30分钟",
    contraindications: "小儿囟门未闭者禁针。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "州圆穴",
    pinyin: "Zhōu Yuán Xué",
    code: "DT.82",
    zone: "十十部位（头面）",
    location: "正会穴旁开一寸",
    location_detail: "在正会穴左右各旁开一寸处。",
    function: "宁心安神，开窍醒脑。主治：失眠、健忘、神经衰弱、精神分裂症。",
    needling_method: "平刺0.5-1寸。",
    depth: "0.5-1寸",
    duration: "20-30分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "水通穴",
    pinyin: "Shuǐ Tōng Xué",
    code: "DT.83",
    zone: "十十部位（头面）",
    location: "嘴角下五分",
    location_detail: "在嘴角直下五分处。",
    function: "调和脾胃，利水消肿。主治：胃痛、呕吐、水肿、小便不利。",
    needling_method: "直刺1-2分。",
    depth: "1-2分",
    duration: "15-20分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "水金穴",
    pinyin: "Shuǐ Jīn Xué",
    code: "DT.84",
    zone: "十十部位（头面）",
    location: "水通穴向内旁开五分",
    location_detail: "在水通穴向内侧旁开五分处。",
    function: "利水渗湿，健脾和胃。主治：水肿、腹水、肾炎、膀胱炎。",
    needling_method: "直刺1-2分。",
    depth: "1-2分",
    duration: "15-20分钟",
    contraindications: "无特殊禁忌。",
    literature: "《董氏针灸正经奇穴学》",
  },

  // ============ 背部部位 ============
  {
    name: "双龙穴",
    pinyin: "Shuāng Lóng Xué",
    code: "DT.91",
    zone: "背部部位",
    location: "背脊正中线，第一胸椎至第七胸椎棘突下",
    location_detail: "在背脊正中线上，从第一胸椎棘突下至第七胸椎棘突下，每椎下一穴，共七穴。",
    function: "清热解毒，活血化瘀。主治：痤疮、青春痘、皮肤瘙痒、带状疱疹。",
    needling_method: "用三棱针点刺出血，然后拔罐。",
    depth: "点刺出血",
    duration: "拔罐5-10分钟",
    contraindications: "出血性疾病患者禁刺。",
    literature: "《董氏针灸正经奇穴学》",
  },
  {
    name: "三金穴",
    pinyin: "Sān Jīn Xué",
    code: "DT.92",
    zone: "背部部位",
    location: "背脊正中线，第三胸椎至第五胸椎棘突下",
    location_detail: "在背脊正中线上，第三胸椎至第五胸椎棘突下，每椎下一穴，共三穴。",
    function: "宣肺止咳，化痰散结。主治：咳嗽、哮喘、支气管炎、肺结核。",
    needling_method: "用三棱针点刺出血，然后拔罐。",
    depth: "点刺出血",
    duration: "拔罐5-10分钟",
    contraindications: "出血性疾病患者禁刺。",
    literature: "《董氏针灸正经奇穴学》",
  },

  // ============ 前胸部位 ============
  {
    name: "喉灵穴",
    pinyin: "Hóu Líng Xué",
    code: "DT.101",
    zone: "前胸部位",
    location: "胸骨柄上切迹（天突穴）旁开一寸",
    location_detail: "在胸骨柄上切迹（天突穴）左右各旁开一寸处。",
    function: "清热利咽，消肿止痛。主治：咽喉炎、扁桃体炎、失音、声带结节。",
    needling_method: "直刺0.3-0.5寸，注意深度。",
    depth: "0.3-0.5寸",
    duration: "15-20分钟",
    contraindications: "不可深刺，防止刺伤肺脏。",
    literature: "《董氏针灸正经奇穴学》",
  },
];

/** 按部位获取董氏奇穴 */
export function getDongAcupointsByZone(zoneCode: string): TcmDongAcupoint[] {
  const zoneName = DONG_ZONES[zoneCode] || "";
  return DONG_ACUPOINTS_DB.filter((a) => a.zone === zoneName);
}

/** 按名称搜索董氏奇穴 */
export function searchDongAcupoints(query: string): TcmDongAcupoint[] {
  const q = query.toLowerCase();
  return DONG_ACUPOINTS_DB.filter(
    (a) =>
      a.name.includes(query) ||
      a.pinyin.toLowerCase().includes(q) ||
      a.code.toLowerCase().includes(q) ||
      a.function.includes(query) ||
      a.location.includes(query)
  );
}

/** 按名称获取董氏奇穴 */
export function getDongAcupointByName(name: string): TcmDongAcupoint | undefined {
  return DONG_ACUPOINTS_DB.find((a) => a.name === name);
}

/** 按编码获取董氏奇穴 */
export function getDongAcupointByCode(code: string): TcmDongAcupoint | undefined {
  return DONG_ACUPOINTS_DB.find((a) => a.code === code);
}

/** 获取所有部位分组 */
export function getDongZoneGroups(): { zoneName: string; acupoints: TcmDongAcupoint[] }[] {
  return Object.entries(DONG_ZONES).map(([code, name]) => ({
    zoneName: name,
    acupoints: DONG_ACUPOINTS_DB.filter((a) => a.zone === name),
  }));
}